config/routes.rb
Rails.application.routes.draw do
  resources :abilities
  resources :players
  root :to => 'players#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability < ApplicationRecord
  belongs_to :player
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
    $exp = [0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000]
    
    def get_lvl
        $exp.each do |lvl|
            if experience <= lvl
                return [$exp.find_index(lvl),$exp[$exp.find_index(lvl)-1],$exp[$exp.find_index(lvl)]]
                break
            end
        end
    end

    def lvl_range
        $exp.each do |lvl|
            if experience <= lvl
                return $exp[lvl]
                break
            end
        end
    end

end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  before_action :set_ability, only: %i[ show edit update destroy ]

  # GET /abilities or /abilities.json
  def index
    @abilities = Ability.all
    @players = Player.all
  end

  # GET /abilities/1 or /abilities/1.json
  def show
  end

  # GET /abilities/new
  def new
    @ability = Ability.new
  end

  # GET /abilities/1/edit
  def edit
  end

  # POST /abilities or /abilities.json
  def create
    @ability = Ability.new(ability_params)

    respond_to do |format|
      if @ability.save
        format.html { redirect_to @ability, notice: "Ability was successfully created." }
        format.json { render :show, status: :created, location: @ability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abilities/1 or /abilities/1.json
  def update
    respond_to do |format|
      if @ability.update(ability_params)
        format.html { redirect_to @ability, notice: "Ability was successfully updated." }
        format.json { render :show, status: :ok, location: @ability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abilities/1 or /abilities/1.json
  def destroy
    @ability.destroy
    respond_to do |format|
      format.html { redirect_to abilities_url, notice: "Ability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ability
      @ability = Ability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ability_params
      params.require(:ability).permit(:name, :level, :experience, :player_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @abilities = Ability.all
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:character_name, :level, :experience, :race, :character_class, :background, :alignment, :player_name)
    end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/abilities/_form.html.erb
<%= form_with(model: ability, local: true) do |form| %>
  <% if ability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ability.errors.count, "error") %> prohibited this ability from being saved:</h2>

      <ul>
        <% ability.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level, min:1%>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.number_field :experience, min:1 %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= collection_select(:ability, :player_id, Player.all, :id, :character_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abilities/edit.html.erb
<h1>Editing Ability</h1>

<%= render 'form', ability: @ability %>

<%= link_to 'Show', @ability %> |
<%= link_to 'Back', abilities_path %>

app/views/abilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Experience</th>
      <th>Character</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abilities.each do |ability| %>
      <tr>
        <td><%= ability.name %></td>
        <td><%= ability.level %></td>
        <td><%= ability.experience %></td>
        <td>
          <% @players.each do |p| %>
            <% if(p.id == ability.player_id)  %>
              <%= p.character_name %>
              <% break %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', ability %></td>
        <td><%= link_to 'Edit', edit_ability_path(ability) %></td>
        <td><%= link_to 'Destroy', ability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ability', new_ability_path %>

app/views/abilities/new.html.erb
<h1>New Ability</h1>

<%= render 'form', ability: @ability %>

<%= link_to 'Back', abilities_path %>

app/views/abilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ability.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @ability.level %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @ability.experience %>
</p>

<p>
  <strong>Player:</strong>
  <%= @ability.player_id %>
</p>

<%= link_to 'Edit', edit_ability_path(@ability) %> |
<%= link_to 'Back', abilities_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Players', players_path() %>
<%= link_to 'Abilities', abilities_path() %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2ee0d2dd5e.js" crossorigin="anonymous"></script>     
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render '/layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :character_name %>
    <%= form.text_field :character_name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level, min:1 %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.number_field :experience, min:0  %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race %>
  </div>

  <div class="field">
    <%= form.label :character_class %>
    <%= form.text_field :character_class %>
  </div>

  <div class="field">
    <%= form.label :background %>
    <%= form.text_field :background %>
  </div>

  <div class="field">
    <%= form.label :alignment %>
    <%= form.text_field :alignment %>
  </div>

  <div class="field">
    <%= form.label :player_name %>
    <%= form.text_field :player_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>
<table class="player-list">
  <thead>
    <tr>
      <th>Character</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
    <tr>
      <td class="sao-container" style="display: flex">
      
      <%= image_tag(player.character_class.downcase, class:'class-icon') %>
      <div class="sao-healthbar">
        <div class="main-container">
          
          <div class="character-name">
            <%= player.character_name %>
          </div>
            <div class="health-bar--outline">
              <div class="health-bar--border">
                <div class="health-bar--background">
                  <%= content_tag(:div, "", class: ["exp-bar--exp"], style: ["--exp:#{player.experience - player.get_lvl[1]};", "--max:#{player.get_lvl[2] - player.get_lvl[1]}"] ) %>
                </div>
              </div>
            </div>
        </div>
        <%= content_tag(:div, "/", class: ["health-indicator"], style: ["--health:'#{player.get_lvl[1]}';", "--max-health:'#{player.get_lvl[2]}';", "--exp:'#{player.experience}'"] ) %>
        <div class="character-level" style="--level: ">
          Lv. <%= player.get_lvl[0] %>
        </div>
      </div>

      <div class="menu">
        <ul class="menu-list">
        <% @abilities.each do |ability| %>
        <% if ability.player_id == player.id%>
          <% case ability.name
              when 'Strength' %>
              <li class="menu-list-item">
                Strength 
                <span class="menu-list-text lvl-edit">
                  <% ability.level = ability.level - 1  %>
                  <%= link_to "", ability_path(ability), :params => {:ability => ability}, method: :put, class: "fas fa-angle-down" %>  
                  <%= ability.level = ability.level + 1  %>  
                  <% ability.level = ability.level + 1  %>
                  <%= link_to "", ability_path(ability), method: :put, class: "fas fa-angle-up", id: "#{player.id}-up-str-#{ability.id}" %>  
                </span>
              </li>
          <%  when 'Dexterity' %>
              <li class="menu-list-item">Dexterity <span class="menu-list-text lvl-edit"><a class="fas fa-angle-down" id="<%= player.id %>-down-dex"></a>  <%= ability.level %>  <span><a class="fas fa-angle-up" id="<%= player.id %>-up-dex-<%= ability.id %>""></a></li>
          <%  when 'Constitution' %>
              <li class="menu-list-item">Constitution <span class="menu-list-text lvl-edit"><a class="fas fa-angle-down" id="<%= player.id %>-down-con"></a>  <%= ability.level %>  <span><a class="fas fa-angle-up" id="<%= player.id %>-up-con-<%= ability.id %>""></a></li>
          <%  when 'Intelligence' %>
              <li class="menu-list-item">Intelligence <span class="menu-list-text lvl-edit"><a class="fas fa-angle-down" id="<%= player.id %>-down-int"></a>  <%= ability.level %>  <span><a class="fas fa-angle-up" id="<%= player.id %>-up-int-<%= ability.id %>""></a></li>
          <%  when 'Wisdom' %>
              <li class="menu-list-item">Wisdom <span class="menu-list-text lvl-edit"><a class="fas fa-angle-down" id="<%= player.id %>-down-wis"></a>  <%= ability.level %>  <span><a class="fas fa-angle-up" id="<%= player.id %>-up-wis-<%= ability.id %>""></a></li>
          <%  when 'Charisma' %>
              <li class="menu-list-item">Charisma <span class="menu-list-text lvl-edit"><a class="fas fa-angle-down" id="<%= player.id %>-down-cha"></a>  <%= ability.level %>  <span><a class="fas fa-angle-up" id="<%= player.id %>-up-cha-<%= ability.id %>""></a></li>
          <% end %>
        <% end %>
      <% end %>
        </ul>
      </div>
      </td>
        <td>
        <%= link_to 'Show', player %><br>
        <%= link_to 'Edit', edit_player_path(player) %><br>
        <%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>


<%= javascript_pack_tag 'main' %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Character name:</strong>
  <%= @player.character_name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @player.level %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @player.experience %>
</p>

<p>
  <strong>Race:</strong>
  <%= @player.race %>
</p>

<p>
  <strong>Character class:</strong>
  <%= @player.character_class %>
</p>

<p>
  <strong>Background:</strong>
  <%= @player.background %>
</p>

<p>
  <strong>Alignment:</strong>
  <%= @player.alignment %>
</p>

<p>
  <strong>Player name:</strong>
  <%= @player.player_name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>